name: Test All 3rd Party Mediation Adapters

# Step 1: Run this manually.
# TODO: Do we want to run this on a cadence?
on: workflow_dispatch

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Install Gradle"
        run: |
          brew install gradle
      - name: "Unit Tests - AppLovin"
        run: |
          cd ThirdPartyAdapters/applovin/
          gradle wrapper
          ./gradlew test --scan
      - name: "Unit Tests - LiftOff"
        run: |
          cd ThirdPartyAdapters/liftoffmonetize/
          gradle wrapper
          ./gradlew test --scan