name: Test All 3rd Party Mediation Adapters

on:
  # Goal 1: Allows you to trigger this workflow manually from the Actions tab
  workflow_dispatch:

  # Goal 1: Runs on a schedule (e.g., every day at 10:00 UTC)
  # Use https://crontab.guru/ to customize the schedule
#  schedule:
#    - cron: '0 10 * * *'

jobs:
  test-adapter:
    # This job will run for each adapter listed in the matrix below
    runs-on: macos-latest
    timeout-minutes: 10 # A timeout per-adapter is safer

    strategy:
      # This matrix defines the list of all your adapters.
      # When you add a new adapter, you only need to add its name here.
      matrix:
        adapter:
          - applovin
          - bidmachine
          - chartboost
          - dtexchange
          - imobile
          - inmobi
          - ironsource
          - liftoffmonetize
          - line
          - maio
          - meta
          - mintegral
          - moloco
          - mytarget
          - pangle
          - pubmatic
          - unity
          - verve

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Install Gradle"
        run: |
          brew install gradle
      - name: "Run Unit Tests for ${{ matrix.adapter }}"
        run: |
          # Use the matrix variable to navigate to the correct directory
          cd ThirdPartyAdapters/${{ matrix.adapter }}/
          gradle wrapper
          ./gradlew test --scan